# Generated by Django 5.2.14 on 2026-05-08 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('robot_id', models.CharField(max_length=128, unique=True, verbose_name='机器人ID')),
                ('token', models.CharField(max_length=256, verbose_name='Telegram Bot Token')),
                ('username', models.CharField(blank=True, default='', max_length=128, verbose_name='机器人用户名')),
                ('first_name', models.CharField(blank=True, default='', max_length=128, verbose_name='昵称')),
                ('owner_user_id', models.CharField(blank=True, default='', max_length=128, verbose_name='归属用户ID')),
                ('webhook_enabled', models.BooleanField(default=True, verbose_name='启用Webhook')),
                ('broadcast_enabled', models.BooleanField(default=True, verbose_name='启用群组播报')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BotGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('chat_id', models.CharField(max_length=128, verbose_name='群组ID')),
                ('title', models.CharField(blank=True, default='群组名称', max_length=255)),
                ('broadcast_enabled', models.BooleanField(default=True, verbose_name='开启收益播报')),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='bots.bot')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('command', models.CharField(blank=True, default='', max_length=100, verbose_name='命令')),
                ('content', models.TextField(blank=True, default='', verbose_name='内容')),
                ('url', models.URLField(blank=True, default='', verbose_name='链接')),
                ('callback_data', models.CharField(blank=True, default='', max_length=255, verbose_name='回调内容')),
                ('type', models.CharField(choices=[('text', '文本'), ('inline', '内嵌按钮')], default='text', max_length=20)),
                ('position', models.CharField(choices=[('message', '消息'), ('button', '按钮')], default='message', max_length=20)),
                ('auto_reply', models.BooleanField(default=False, verbose_name='自动回复')),
                ('sort', models.IntegerField(default=0)),
                ('row_place', models.IntegerField(default=0)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='bots.bot', verbose_name='机器人')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
