# Generated by Django 5.2.14 on 2026-05-08 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TgUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('user_id', models.CharField(max_length=128, unique=True, verbose_name='Telegram用户ID')),
                ('bot_id', models.CharField(blank=True, default='', max_length=128, verbose_name='机器人ID')),
                ('username', models.CharField(blank=True, default='', max_length=128, verbose_name='用户名')),
                ('first_name', models.CharField(blank=True, default='', max_length=128, verbose_name='昵称')),
                ('inviter_id', models.CharField(blank=True, default='', max_length=128, verbose_name='邀请人ID')),
                ('member_level', models.CharField(blank=True, default='', max_length=64, verbose_name='会员等级')),
                ('member_expire_at', models.DateTimeField(blank=True, null=True, verbose_name='会员到期时间')),
                ('is_blacklisted', models.BooleanField(default=False, verbose_name='拉黑')),
                ('is_top', models.BooleanField(default=False, verbose_name='置顶')),
                ('total_recharge', models.DecimalField(decimal_places=8, default=0, max_digits=30, verbose_name='累计充值')),
                ('total_consumption', models.DecimalField(decimal_places=8, default=0, max_digits=30, verbose_name='累计消费')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserTop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('user_id', models.CharField(max_length=128, verbose_name='用户ID')),
                ('bot_id', models.CharField(blank=True, default='', max_length=128, verbose_name='机器人ID')),
                ('rank_type', models.CharField(default='recharge', max_length=50, verbose_name='排行类型')),
                ('amount', models.DecimalField(decimal_places=8, default=0, max_digits=30, verbose_name='金额')),
                ('rank', models.PositiveIntegerField(default=0, verbose_name='排名')),
                ('snapshot_date', models.DateField(blank=True, null=True, verbose_name='快照日期')),
            ],
            options={
                'indexes': [models.Index(fields=['bot_id', 'rank_type', 'rank'], name='tgusers_use_bot_id_7b7964_idx')],
            },
        ),
    ]
