# Generated by Django 5.2.14 on 2026-05-08 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemberGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('name', models.CharField(max_length=100)),
                ('duration_days', models.PositiveIntegerField(default=30)),
                ('sell_amount', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('min_limit', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('max_limit', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MemberOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('order_no', models.CharField(max_length=64, unique=True)),
                ('user_id', models.CharField(max_length=128)),
                ('target_user_id', models.CharField(blank=True, default='', max_length=128)),
                ('pay_type', models.CharField(default='usdt', max_length=20)),
                ('amount', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('txid', models.CharField(blank=True, default='', max_length=128)),
                ('status', models.CharField(choices=[('pending', '待支付'), ('paid', '已支付'), ('activated', '已开通'), ('cancelled', '已取消')], default='pending', max_length=20)),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='membership.membergoods')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
