# Generated by Django 5.2.14 on 2026-05-08 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('title', models.CharField(max_length=128)),
                ('bot_id', models.CharField(blank=True, default='', max_length=128)),
                ('activity_type', models.CharField(default='recharge', max_length=50)),
                ('reward_amount', models.DecimalField(decimal_places=8, default=0, max_digits=30)),
                ('reward_token', models.CharField(default='usdt', max_length=20)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('rule', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MemberCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('user_id', models.CharField(max_length=128)),
                ('inviter_id', models.CharField(blank=True, default='', max_length=128)),
                ('bot_id', models.CharField(blank=True, default='', max_length=128)),
                ('source_order_no', models.CharField(blank=True, default='', max_length=64)),
                ('amount', models.DecimalField(decimal_places=8, default=0, max_digits=30)),
                ('token_type', models.CharField(default='usdt', max_length=20)),
                ('status', models.CharField(default='pending', max_length=20)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MemberRecharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('order_no', models.CharField(max_length=64, unique=True)),
                ('user_id', models.CharField(max_length=128)),
                ('bot_id', models.CharField(blank=True, default='', max_length=128)),
                ('amount', models.DecimalField(decimal_places=8, default=0, max_digits=30)),
                ('token_type', models.CharField(default='usdt', max_length=20)),
                ('txid', models.CharField(blank=True, default='', max_length=128)),
                ('status', models.CharField(default='pending', max_length=20)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
