# Generated by Django 5.2.14 on 2026-05-10 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LegacyGameRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('resource', models.CharField(db_index=True, max_length=100, verbose_name='旧版资源名')),
                ('table_name', models.CharField(db_index=True, max_length=100, verbose_name='旧版表名')),
                ('legacy_id', models.CharField(db_index=True, max_length=255, verbose_name='旧版ID')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='旧版字段数据')),
            ],
            options={
                'verbose_name': '旧版TRX质押记录',
                'verbose_name_plural': '旧版TRX质押记录',
                'indexes': [models.Index(fields=['resource', 'is_active'], name='legacy_lega_resourc_48dae6_idx'), models.Index(fields=['table_name', 'legacy_id'], name='legacy_lega_table_n_ab3108_idx')],
                'unique_together': {('resource', 'legacy_id')},
            },
        ),
    ]
