# Generated by Django 5.2.14 on 2026-05-08 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('user_id', models.CharField(max_length=128, unique=True)),
                ('bot_id', models.CharField(blank=True, default='', max_length=128)),
                ('trx', models.DecimalField(decimal_places=8, default=0, max_digits=30)),
                ('usdt', models.DecimalField(decimal_places=8, default=0, max_digits=30)),
                ('integral', models.DecimalField(decimal_places=8, default=0, max_digits=30)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RunningWater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('user_id', models.CharField(max_length=128)),
                ('bot_id', models.CharField(blank=True, default='', max_length=128)),
                ('business_type', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=30)),
                ('token_type', models.CharField(default='usdt', max_length=20)),
                ('before_balance', models.DecimalField(decimal_places=8, default=0, max_digits=30)),
                ('after_balance', models.DecimalField(decimal_places=8, default=0, max_digits=30)),
                ('ref_no', models.CharField(blank=True, default='', max_length=128)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('user_id', models.CharField(max_length=128)),
                ('address', models.CharField(max_length=64)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=30)),
                ('token_type', models.CharField(default='usdt', max_length=20)),
                ('status', models.CharField(choices=[('pending', '待审批'), ('approved', '已通过'), ('rejected', '已拒绝'), ('paid', '已打款')], default='pending', max_length=20)),
                ('txid', models.CharField(blank=True, default='', max_length=128)),
                ('reviewed_by', models.CharField(blank=True, default='', max_length=128)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
