# Generated by Django 5.2.14 on 2026-05-08 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TextConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('key', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='配置键')),
                ('label', models.CharField(blank=True, default='', max_length=200, verbose_name='显示名称')),
                ('value', models.TextField(blank=True, default='', verbose_name='配置值')),
                ('default_value', models.TextField(blank=True, default='', verbose_name='默认值')),
                ('category', models.CharField(blank=True, db_index=True, default='ui', max_length=80, verbose_name='分类')),
                ('description', models.TextField(blank=True, default='', verbose_name='说明')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '文字配置',
                'verbose_name_plural': '文字配置',
                'ordering': ['category', 'sort', 'key'],
            },
        ),
    ]
