import type { RouteRecordRaw } from 'vue-router';

const routes: RouteRecordRaw[] = [
  {
    name: 'Tron',
    path: '/tron',
    redirect: '/tron/dashboard',
    meta: { icon: 'cryptocurrency-color:trx', order: -10, title: 'TRON后台' },
    children: [
      { name: 'TronDashboard', path: '/tron/dashboard', component: () => import('#/views/tron/Dashboard.vue'), meta: { affixTab: true, icon: 'lucide:layout-dashboard', title: '控制台' } },
      { name: 'TronSettings', path: '/tron/settings', component: () => import('#/views/tron/Settings.vue'), meta: { icon: 'lucide:settings', title: '系统配置' } },
      { name: 'TronBots', path: '/tron/resource/bots', component: () => import('#/views/tron/ResourcePage.vue'), meta: { icon: 'lucide:bot', title: '机器人管理' }, props: { key: 'bots' } },
      { name: 'TronPromotions', path: '/tron/resource/promotions', component: () => import('#/views/tron/ResourcePage.vue'), meta: { icon: 'lucide:megaphone', title: '推广文案' }, props: { key: 'promotions' } },
      { name: 'TronBotGroups', path: '/tron/resource/botGroups', component: () => import('#/views/tron/ResourcePage.vue'), meta: { icon: 'lucide:users', title: '群组管理' }, props: { key: 'botGroups' } },
      { name: 'TronAddresses', path: '/tron/resource/addresses', component: () => import('#/views/tron/ResourcePage.vue'), meta: { icon: 'lucide:wallet-cards', title: '地址池' }, props: { key: 'addresses' } },
      { name: 'TronExchangeOrders', path: '/tron/resource/exchangeOrders', component: () => import('#/views/tron/ResourcePage.vue'), meta: { icon: 'lucide:refresh-cw', title: '兑换订单' }, props: { key: 'exchangeOrders' } },
      { name: 'TronExchangeBlacklist', path: '/tron/resource/exchangeBlacklist', component: () => import('#/views/tron/ResourcePage.vue'), meta: { icon: 'lucide:ban', title: '兑换黑名单' }, props: { key: 'exchangeBlacklist' } },
      { name: 'TronEnergyPlans', path: '/tron/resource/energyPlans', component: () => import('#/views/tron/ResourcePage.vue'), meta: { icon: 'lucide:zap', title: '能量套餐' }, props: { key: 'energyPlans' } },
      { name: 'TronEnergyOrders', path: '/tron/resource/energyOrders', component: () => import('#/views/tron/ResourcePage.vue'), meta: { icon: 'lucide:bolt', title: '能量订单' }, props: { key: 'energyOrders' } },
      { name: 'TronMemberGoods', path: '/tron/resource/memberGoods', component: () => import('#/views/tron/ResourcePage.vue'), meta: { icon: 'lucide:badge-vip', title: '会员商品' }, props: { key: 'memberGoods' } },
      { name: 'TronMemberOrders', path: '/tron/resource/memberOrders', component: () => import('#/views/tron/ResourcePage.vue'), meta: { icon: 'lucide:shopping-bag', title: '会员订单' }, props: { key: 'memberOrders' } },
      { name: 'TronBalances', path: '/tron/resource/balances', component: () => import('#/views/tron/ResourcePage.vue'), meta: { icon: 'lucide:circle-dollar-sign', title: '用户余额' }, props: { key: 'balances' } },
      { name: 'TronRunningWater', path: '/tron/resource/runningWater', component: () => import('#/views/tron/ResourcePage.vue'), meta: { icon: 'lucide:list', title: '资金流水' }, props: { key: 'runningWater' } },
      { name: 'TronWithdrawals', path: '/tron/resource/withdrawals', component: () => import('#/views/tron/ResourcePage.vue'), meta: { icon: 'lucide:banknote-arrow-up', title: '提现审核' }, props: { key: 'withdrawals' } },
      { name: 'TronUsers', path: '/tron/resource/users', component: () => import('#/views/tron/ResourcePage.vue'), meta: { icon: 'lucide:user-round', title: '用户管理' }, props: { key: 'users' } },
      { name: 'TronUserTops', path: '/tron/resource/userTops', component: () => import('#/views/tron/ResourcePage.vue'), meta: { icon: 'lucide:trophy', title: '用户排行' }, props: { key: 'userTops' } },
      { name: 'TronListenAddresses', path: '/tron/resource/listenAddresses', component: () => import('#/views/tron/ResourcePage.vue'), meta: { icon: 'lucide:radar', title: '监听地址' }, props: { key: 'listenAddresses' } },
      { name: 'TronTransactions', path: '/tron/resource/transactions', component: () => import('#/views/tron/ResourcePage.vue'), meta: { icon: 'lucide:scan-line', title: '链上交易' }, props: { key: 'transactions' } },
      { name: 'TronEnergyAgentRecords', path: '/tron/resource/energyAgentRecords', component: () => import('#/views/tron/ResourcePage.vue'), meta: { icon: 'lucide:hand-coins', title: '能量代理记录' }, props: { key: 'energyAgentRecords' } },
      { name: 'TronEnergyAdvanceRecords', path: '/tron/resource/energyAdvanceRecords', component: () => import('#/views/tron/ResourcePage.vue'), meta: { icon: 'lucide:receipt-text', title: '预支记录' }, props: { key: 'energyAdvanceRecords' } },
      { name: 'TronEnergyAddressConfigs', path: '/tron/resource/energyAddressConfigs', component: () => import('#/views/tron/ResourcePage.vue'), meta: { icon: 'lucide:server-cog', title: '能量地址配置' }, props: { key: 'energyAddressConfigs' } },
      { name: 'TronMemberRecharges', path: '/tron/resource/memberRecharges', component: () => import('#/views/tron/ResourcePage.vue'), meta: { icon: 'lucide:badge-dollar-sign', title: '会员充值' }, props: { key: 'memberRecharges' } },
      { name: 'TronMemberActivities', path: '/tron/resource/memberActivities', component: () => import('#/views/tron/ResourcePage.vue'), meta: { icon: 'lucide:party-popper', title: '会员活动' }, props: { key: 'memberActivities' } },
      { name: 'TronMemberCommissions', path: '/tron/resource/memberCommissions', component: () => import('#/views/tron/ResourcePage.vue'), meta: { icon: 'lucide:network', title: '会员佣金' }, props: { key: 'memberCommissions' } },
      { name: 'TronEnergyHourlyTimes', path: '/tron/resource/energyHourlyTimes', component: () => import('#/views/tron/ResourcePage.vue'), meta: { icon: 'lucide:clock', title: '能量时长配置' }, props: { key: 'energyHourlyTimes' } },
      { name: 'TronEnergyHourlyTimePrices', path: '/tron/resource/energyHourlyTimePrices', component: () => import('#/views/tron/ResourcePage.vue'), meta: { icon: 'lucide:badge-cent', title: '能量时长价格' }, props: { key: 'energyHourlyTimePrices' } },
      { name: 'TronEnergyPenPlans', path: '/tron/resource/energyPenPlans', component: () => import('#/views/tron/ResourcePage.vue'), meta: { icon: 'lucide:list-ordered', title: '能量笔数套餐' }, props: { key: 'energyPenPlans' } },
      { name: 'TronNumberOfOrders', path: '/tron/resource/numberOfOrders', component: () => import('#/views/tron/ResourcePage.vue'), meta: { icon: 'lucide:hash', title: '笔数订单/次数' }, props: { key: 'numberOfOrders' } },
      { name: 'TronEnergyPenFlashEntries', path: '/tron/resource/energyPenFlashEntries', component: () => import('#/views/tron/ResourcePage.vue'), meta: { icon: 'lucide:zap', title: '能量闪租入口' }, props: { key: 'energyPenFlashEntries' } },
      { name: 'TronEnergyIntelligentPlans', path: '/tron/resource/energyIntelligentPlans', component: () => import('#/views/tron/ResourcePage.vue'), meta: { icon: 'lucide:brain-circuit', title: '智能托管套餐' }, props: { key: 'energyIntelligentPlans' } },
      { name: 'TronEnergyRecords', path: '/tron/resource/energyRecords', component: () => import('#/views/tron/ResourcePage.vue'), meta: { icon: 'lucide:file-clock', title: '能量租赁记录' }, props: { key: 'energyRecords' } },
      { name: 'TronExchangeRecords', path: '/tron/resource/exchangeRecords', component: () => import('#/views/tron/ResourcePage.vue'), meta: { icon: 'lucide:repeat-2', title: '兑换记录' }, props: { key: 'exchangeRecords' } },
      { name: 'TronRechargeConfigs', path: '/tron/resource/rechargeConfigs', component: () => import('#/views/tron/ResourcePage.vue'), meta: { icon: 'lucide:wallet-minimal', title: '充值配置' }, props: { key: 'rechargeConfigs' } },
    ],
  },
];

export default routes;
