# Generated by Django 5.2.14 on 2026-05-08 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeBlacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('address', models.CharField(max_length=64, unique=True)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExchangeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('bot_id', models.CharField(blank=True, default='', max_length=128)),
                ('usdt_to_trx_rate', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('trx_to_usdt_rate', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('float_rate', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='上浮费率')),
                ('max_limit', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('min_limit', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('auto_mode', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExchangeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('order_no', models.CharField(max_length=64, unique=True)),
                ('bot_id', models.CharField(blank=True, default='', max_length=128)),
                ('user_id', models.CharField(blank=True, default='', max_length=128)),
                ('address', models.CharField(blank=True, default='', max_length=64)),
                ('amount', models.DecimalField(decimal_places=8, default=0, max_digits=30)),
                ('return_amount', models.DecimalField(decimal_places=8, default=0, max_digits=30)),
                ('type', models.CharField(choices=[('usdt_to_trx', 'USDT兑换TRX'), ('trx_to_usdt', 'TRX兑换USDT')], max_length=20)),
                ('status', models.CharField(choices=[('pending', '待支付'), ('paid', '已支付'), ('sent', '已出款'), ('cancelled', '已取消'), ('failed', '失败')], default='pending', max_length=20)),
                ('pay_txid', models.CharField(blank=True, default='', max_length=128)),
                ('payout_txid', models.CharField(blank=True, default='', max_length=128)),
                ('profit_usdt', models.DecimalField(decimal_places=8, default=0, max_digits=30)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
