# Generated by Django 5.2.14 on 2026-05-08 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('order_no', models.CharField(max_length=64, unique=True)),
                ('bot_id', models.CharField(blank=True, default='', max_length=128)),
                ('user_id', models.CharField(blank=True, default='', max_length=128)),
                ('from_token', models.CharField(default='usdt', max_length=20)),
                ('to_token', models.CharField(default='trx', max_length=20)),
                ('from_amount', models.DecimalField(decimal_places=8, default=0, max_digits=30)),
                ('to_amount', models.DecimalField(decimal_places=8, default=0, max_digits=30)),
                ('rate', models.DecimalField(decimal_places=8, default=0, max_digits=30)),
                ('fee', models.DecimalField(decimal_places=8, default=0, max_digits=30)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('pay_txid', models.CharField(blank=True, default='', max_length=128)),
                ('payout_txid', models.CharField(blank=True, default='', max_length=128)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
