# Generated by Django 5.2.14 on 2026-05-08 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('address', models.CharField(max_length=64, unique=True, verbose_name='TRON地址')),
                ('private_key_encrypted', models.TextField(blank=True, default='', verbose_name='加密私钥')),
                ('address_type', models.CharField(choices=[('exchange', '兑换'), ('energy', '能量'), ('member', '会员'), ('listen', '监听')], default='exchange', max_length=20)),
                ('user_id', models.CharField(blank=True, default='', max_length=128, verbose_name='Telegram用户ID')),
                ('username', models.CharField(blank=True, default='', max_length=128, verbose_name='用户名')),
                ('bot_id', models.CharField(blank=True, default='', max_length=128, verbose_name='机器人ID')),
                ('allocated', models.BooleanField(default=False, verbose_name='已分配')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChainTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('txid', models.CharField(max_length=128, unique=True, verbose_name='交易Hash')),
                ('from_address', models.CharField(blank=True, default='', max_length=64)),
                ('to_address', models.CharField(blank=True, default='', max_length=64)),
                ('amount', models.DecimalField(decimal_places=8, default=0, max_digits=30)),
                ('token_type', models.CharField(choices=[('trx', 'TRX'), ('usdt', 'USDT'), ('energy', '能量')], default='usdt', max_length=20)),
                ('confirmed', models.BooleanField(default=False)),
                ('raw', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
