# Generated by Django 5.2.14 on 2026-05-08 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListenAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('bot_id', models.CharField(blank=True, default='', max_length=128)),
                ('address', models.CharField(max_length=64, unique=True)),
                ('label', models.CharField(blank=True, default='', max_length=128)),
                ('token_type', models.CharField(default='usdt', max_length=20)),
                ('min_amount', models.DecimalField(decimal_places=8, default=0, max_digits=30)),
                ('enabled', models.BooleanField(default=True)),
                ('last_scanned_txid', models.CharField(blank=True, default='', max_length=128)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
