# Generated by Django 5.2.14 on 2026-05-08 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_listenaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaintransaction',
            name='listen_address',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='chaintransaction',
            name='matched_business',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='chaintransaction',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chaintransaction',
            name='ref_no',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
