RESOURCE_TABLE_MAP = {
    "tgAdvanceRecord": "tg_advance_record",
    "tgConfig": "tg_config",
    "tgEnergyAgentRecord": "tg_energy_agent_record",
    "tgEnergyHourly": "tg_energy_hourly",
    "tgEnergyHourlyTime": "tg_energy_hourly_time",
    "tgEnergyHourlyTimePice": "tg_energy_hourly_time_pice",
    "tgEnergyIntelligent": "tg_energy_intelligent",
    "tgEnergyIntelligentAddress": "tg_energy_intelligent_address",
    "tgEnergyPen": "tg_energy_pen",
    "tgEnergyPenAddress": "tg_energy_pen_address",
    "tgEnergyPenFlashEnt": "tg_energy_pen_flash_ent",
    "tgEnergyRecord": "tg_energy_record",
    "tgExchange": "tg_exchange",
    "tgExchangeBlack": "tg_exchange_black",
    "tgExchangeRecord": "tg_exchange_record",
    "tgGroup": "tg_group",
    "tgListerAddress": "tg_lister_address",
    "tgMemberActivity": "tg_member_activity",
    "tgMemberGoods": "tg_member_goods",
    "tgMemberOrder": "tg_member_order",
    "tgMemberRecharge": "tg_member_recharge",
    "tgNumberOfOrders": "tg_number_of_orders",
    "tgPromotion": "tg_promotion",
    "tgRechargeConfig": "tg_recharge_config",
    "tgRunningWater": "tg_running_water",
    "tgUser": "tg_user",
    "tgUserTop": "tg_user_top",
}

TABLE_RESOURCE_MAP = {table: resource for resource, table in RESOURCE_TABLE_MAP.items()}

RESOURCE_TITLES = {
    "tgAdvanceRecord": "预支记录",
    "tgConfig": "系统配置/质押配置",
    "tgEnergyAgentRecord": "能量代理记录",
    "tgEnergyHourly": "小时能量闪租配置",
    "tgEnergyHourlyTime": "时长能量文案配置",
    "tgEnergyHourlyTimePice": "时长能量价格",
    "tgEnergyIntelligent": "智能托管配置",
    "tgEnergyIntelligentAddress": "智能托管地址",
    "tgEnergyPen": "能量笔数套餐",
    "tgEnergyPenAddress": "笔数能量地址",
    "tgEnergyPenFlashEnt": "笔数/闪租入口配置",
    "tgEnergyRecord": "能量租赁记录",
    "tgExchange": "兑换配置",
    "tgExchangeBlack": "兑换黑名单",
    "tgExchangeRecord": "兑换记录",
    "tgGroup": "群组管理",
    "tgListerAddress": "监听地址",
    "tgMemberActivity": "会员活动",
    "tgMemberGoods": "会员商品",
    "tgMemberOrder": "会员订单",
    "tgMemberRecharge": "会员充值",
    "tgNumberOfOrders": "笔数次数记录",
    "tgPromotion": "推广配置",
    "tgRechargeConfig": "充值配置",
    "tgRunningWater": "资金流水",
    "tgUser": "用户管理",
    "tgUserTop": "用户排行",
}
