# Generated by Django 5.2.14 on 2026-05-08 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('order_no', models.CharField(max_length=64, unique=True)),
                ('bot_id', models.CharField(blank=True, default='', max_length=128)),
                ('user_id', models.CharField(blank=True, default='', max_length=128)),
                ('receiver_address', models.CharField(max_length=64)),
                ('energy_amount', models.PositiveIntegerField(default=0)),
                ('trx_amount', models.DecimalField(decimal_places=8, default=0, max_digits=30)),
                ('usdt_amount', models.DecimalField(decimal_places=8, default=0, max_digits=30)),
                ('pay_type', models.CharField(default='balance', max_length=20)),
                ('status', models.CharField(choices=[('pending', '待支付'), ('paid', '已支付'), ('delegating', '委托中'), ('success', '成功'), ('failed', '失败'), ('expired', '已过期')], default='pending', max_length=20)),
                ('pay_txid', models.CharField(blank=True, default='', max_length=128)),
                ('energy_txid', models.CharField(blank=True, default='', max_length=128)),
                ('platform_order_id', models.CharField(blank=True, default='', max_length=128)),
                ('callback_payload', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EnergyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('bot_id', models.CharField(blank=True, default='', max_length=128)),
                ('name', models.CharField(max_length=100)),
                ('mode', models.CharField(choices=[('hourly', '能量闪租'), ('duration', '时长套餐'), ('times', '笔数套餐'), ('smart', '智能托管')], max_length=20)),
                ('energy_amount', models.PositiveIntegerField(default=32000)),
                ('duration_hours', models.PositiveIntegerField(default=1)),
                ('number_of_times', models.PositiveIntegerField(default=0)),
                ('price_trx', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('price_usdt', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('sort', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EnergyCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('exchange_rate', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('profit_usdt', models.DecimalField(decimal_places=8, default=0, max_digits=30)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='energy.energyorder')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='energyorder',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='energy.energyplan'),
        ),
    ]
