# Generated by Django 5.2.14 on 2026-05-08 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('user_id', models.CharField(max_length=128)),
                ('bot_id', models.CharField(blank=True, default='', max_length=128)),
                ('amount', models.DecimalField(decimal_places=8, default=0, max_digits=30)),
                ('token_type', models.CharField(default='trx', max_length=20)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('reason', models.TextField(blank=True, default='')),
                ('reviewed_by', models.CharField(blank=True, default='', max_length=128)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EnergyAddressConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('bot_id', models.CharField(blank=True, default='', max_length=128)),
                ('address', models.CharField(max_length=64)),
                ('private_key_encrypted', models.TextField(blank=True, default='')),
                ('mode', models.CharField(choices=[('pen', '笔数地址'), ('smart', '智能托管地址'), ('hourly', '闪租地址')], default='pen', max_length=20)),
                ('max_energy', models.PositiveIntegerField(default=0)),
                ('used_energy', models.PositiveIntegerField(default=0)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EnergyAgentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('order_no', models.CharField(max_length=64, unique=True)),
                ('bot_id', models.CharField(blank=True, default='', max_length=128)),
                ('agent_user_id', models.CharField(blank=True, default='', max_length=128)),
                ('user_id', models.CharField(blank=True, default='', max_length=128)),
                ('receiver_address', models.CharField(blank=True, default='', max_length=64)),
                ('energy_amount', models.PositiveIntegerField(default=0)),
                ('cost_trx', models.DecimalField(decimal_places=8, default=0, max_digits=30)),
                ('profit_trx', models.DecimalField(decimal_places=8, default=0, max_digits=30)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('txid', models.CharField(blank=True, default='', max_length=128)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
