# Generated by Django 5.2.14 on 2026-05-08 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0002_advancerecord_energyaddressconfig_energyagentrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyHourlyTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('bot_id', models.CharField(blank=True, default='', max_length=128)),
                ('name', models.CharField(max_length=100)),
                ('hours', models.PositiveIntegerField(default=1)),
                ('enabled', models.BooleanField(default=True)),
                ('sort', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EnergyIntelligentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('bot_id', models.CharField(blank=True, default='', max_length=128)),
                ('name', models.CharField(max_length=100)),
                ('min_energy', models.PositiveIntegerField(default=0)),
                ('max_energy', models.PositiveIntegerField(default=0)),
                ('price_trx', models.DecimalField(decimal_places=8, default=0, max_digits=30)),
                ('strategy', models.CharField(default='auto', max_length=50)),
                ('enabled', models.BooleanField(default=True)),
                ('sort', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EnergyPenFlashEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('bot_id', models.CharField(blank=True, default='', max_length=128)),
                ('title', models.CharField(max_length=128)),
                ('address', models.CharField(blank=True, default='', max_length=64)),
                ('energy_amount', models.PositiveIntegerField(default=0)),
                ('price_trx', models.DecimalField(decimal_places=8, default=0, max_digits=30)),
                ('enabled', models.BooleanField(default=True)),
                ('sort', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EnergyPenPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('bot_id', models.CharField(blank=True, default='', max_length=128)),
                ('name', models.CharField(max_length=100)),
                ('number_of_times', models.PositiveIntegerField(default=1)),
                ('energy_amount', models.PositiveIntegerField(default=32000)),
                ('price_trx', models.DecimalField(decimal_places=8, default=0, max_digits=30)),
                ('price_usdt', models.DecimalField(decimal_places=8, default=0, max_digits=30)),
                ('enabled', models.BooleanField(default=True)),
                ('sort', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EnergyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('order_no', models.CharField(max_length=64, unique=True)),
                ('bot_id', models.CharField(blank=True, default='', max_length=128)),
                ('user_id', models.CharField(blank=True, default='', max_length=128)),
                ('receiver_address', models.CharField(blank=True, default='', max_length=64)),
                ('mode', models.CharField(default='hourly', max_length=20)),
                ('energy_amount', models.PositiveIntegerField(default=0)),
                ('duration_hours', models.PositiveIntegerField(default=0)),
                ('number_of_times', models.PositiveIntegerField(default=0)),
                ('amount_trx', models.DecimalField(decimal_places=8, default=0, max_digits=30)),
                ('txid', models.CharField(blank=True, default='', max_length=128)),
                ('status', models.CharField(default='pending', max_length=20)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NumberOfOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('bot_id', models.CharField(blank=True, default='', max_length=128)),
                ('user_id', models.CharField(blank=True, default='', max_length=128)),
                ('available_times', models.PositiveIntegerField(default=0)),
                ('used_times', models.PositiveIntegerField(default=0)),
                ('source_order_no', models.CharField(blank=True, default='', max_length=64)),
                ('expire_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EnergyHourlyTimePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('bot_id', models.CharField(blank=True, default='', max_length=128)),
                ('energy_amount', models.PositiveIntegerField(default=32000)),
                ('price_trx', models.DecimalField(decimal_places=8, default=0, max_digits=30)),
                ('price_usdt', models.DecimalField(decimal_places=8, default=0, max_digits=30)),
                ('enabled', models.BooleanField(default=True)),
                ('time', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='energy.energyhourlytime')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
