# Generated by Django 5.2.14 on 2026-05-09 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0003_energyhourlytime_energyintelligentplan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StakingAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('bot_id', models.CharField(blank=True, default='', max_length=128)),
                ('address', models.CharField(max_length=64, unique=True, verbose_name='质押地址')),
                ('private_key_encrypted', models.TextField(blank=True, default='', verbose_name='主签私钥/密文')),
                ('multisig_private_keys', models.TextField(blank=True, default='', verbose_name='多签私钥/密文，一行一个')),
                ('permission_id', models.PositiveIntegerField(default=0, verbose_name='Active Permission ID，0 表示 owner/default')),
                ('required_signature_count', models.PositiveIntegerField(default=1, verbose_name='本系统签名数量要求')),
                ('resource', models.CharField(choices=[('ENERGY', '能量'), ('BANDWIDTH', '带宽')], default='ENERGY', max_length=20)),
                ('frozen_balance_sun', models.BigIntegerField(default=0, verbose_name='已质押 SUN')),
                ('max_delegable_sun', models.BigIntegerField(default=0, verbose_name='最大可委托 SUN')),
                ('delegated_balance_sun', models.BigIntegerField(default=0, verbose_name='已委托 SUN')),
                ('max_energy', models.PositiveIntegerField(default=0, verbose_name='最大能量')),
                ('used_energy', models.PositiveIntegerField(default=0, verbose_name='已用能量')),
                ('min_reserve_energy', models.PositiveIntegerField(default=0, verbose_name='保留能量')),
                ('auto_reclaim', models.BooleanField(default=True)),
                ('enabled', models.BooleanField(default=True)),
                ('last_sync_payload', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StakingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('order_no', models.CharField(max_length=64, unique=True)),
                ('receiver_address', models.CharField(max_length=64)),
                ('resource', models.CharField(default='ENERGY', max_length=20)),
                ('energy_amount', models.PositiveIntegerField(default=0)),
                ('delegate_balance_sun', models.BigIntegerField(default=0)),
                ('lock', models.BooleanField(default=False)),
                ('lock_period', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', '待处理'), ('delegating', '委托中'), ('success', '已委托'), ('failed', '失败'), ('reclaiming', '回收中'), ('reclaimed', '已回收')], default='pending', max_length=20)),
                ('delegate_txid', models.CharField(blank=True, default='', max_length=128)),
                ('undelegate_txid', models.CharField(blank=True, default='', max_length=128)),
                ('expire_at', models.DateTimeField(blank=True, null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staking_orders', to='energy.stakingaccount')),
                ('energy_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staking_orders', to='energy.energyorder')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StakingTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('operation', models.CharField(choices=[('stake', '质押'), ('unstake', '解押'), ('delegate', '委托'), ('undelegate', '回收')], max_length=20)),
                ('resource', models.CharField(default='ENERGY', max_length=20)),
                ('amount_sun', models.BigIntegerField(default=0)),
                ('receiver_address', models.CharField(blank=True, default='', max_length=64)),
                ('permission_id', models.PositiveIntegerField(default=0)),
                ('signature_count', models.PositiveIntegerField(default=0)),
                ('txid', models.CharField(blank=True, default='', max_length=128)),
                ('status', models.CharField(default='built', max_length=20)),
                ('broadcast_result', models.JSONField(blank=True, default=dict)),
                ('raw_transaction', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='energy.stakingaccount')),
                ('staking_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='energy.stakingorder')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
